# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: f88a76af
    url: /
    weight: 10
  - name: Papers
    identifier: 2c5747da
    url: /#papers
    weight: 20
  - name: Talks
    identifier: b6edf42c
    url: /#talks
    weight: 30
  - name: News
    identifier: b3dde7b7
    url: /#news
    weight: 40
  - name: Experience
    identifier: 399e6c5e
    url: experience/
    weight: 50
  - name: Projects
    identifier: 5534a080
    url: projects/
    weight: 60
  - name: Courses
    identifier: "75821258"
    url: courses/
    weight: 70
  - name: Contact
    identifier: contact
    url: /#contact
    weight: 80
