# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: home
    url: /
    weight: 10
  - name: Papers
    identifier: 2c5747da
    url: /#papers
    weight: 20
  # - name: News
  #   identifier: b3dde7b7
  #   url: /#news
  #   weight: 30
  - name: CV
    identifier: 399e6c5e
    url: /cv
    weight: 40
