hugoblox:
  schema: "2.0"
  identity:
    name: Mathilde Tissot
    type: person
    tagline: PhD student | Cancer biology and radiotherapy
    description: |-
      3rd-year PhD student in the PRISME lab (IP2I, Lyon).
      Focused on hadrontherapy and cell biology of head and neck cancers !
  theme:
    mode: default
    pack: matcha
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: false
    theme_toggle: true
    cta:
      enable: true
      text: Contact
      url: /mathildetissot/contact/
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
    suggestions:
  seo:
    location:
      address:
        street: 165 Chemin du Grand Revoyet
        city: Oullins-Pierre-Bénite
        postal_code: "69310"
        country: FRANCE
    ai:
      allow:
        - /
    title: Mathilde Tissot
  verification: { google: XSUABHaOWN52nmhpr5x1GlgD18Mdlxs5wno8QhNdscM, bing: "A3D404396C7A7FD1D11F3CBBD5AAE8D5" }
  analytics:
    google:
      measurement_id: G-KH711G1Q3J
